version: '3.8'
services:
  postgres:
    image: postgres:10.4
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
